// Code generated by git.sr.ht/~shulhan/pakakeh.go/lib/memfs DO NOT EDIT.

package haminer

import (
	"git.sr.ht/~shulhan/pakakeh.go/lib/memfs"
)

func generate__wui() *memfs.Node {
	var node = &memfs.Node{
		SysPath:     "_wui",
		Path:        "/",
		ContentType: "",
		GenFuncName: "generate__wui",
	}
	node.SetMode(0o20000000755)
	node.SetModTimeUnix(1736274272, 854141700)
	node.SetName("/")
	node.SetSize(0)
	return node
}

// _memfsWUI_getNode is internal function to minimize duplicate node
// created on Node.AddChild() and on generatedPathNode.Set().
func _memfsWUI_getNode(mfs *memfs.MemFS, path string, fn func() *memfs.Node) (node *memfs.Node) {
	node = mfs.PathNodes.Get(path)
	if node != nil {
		return node
	}
	return fn()
}

func init() {
	memfsWUI = &memfs.MemFS{
		PathNodes: memfs.NewPathNode(),
		Opts: &memfs.Options{
			Root:        "_wui",
			MaxFileSize: 5242880,
			Includes:    []string{
				`.*\.(html|js)$`,
			},
			Excludes: []string{
			},
			Embed: memfs.EmbedOptions{
				CommentHeader:  ``,
				PackageName:    "haminer",
				VarName:        "memfsWUI",
				GoFileName:     "memfs_wui.go",
				WithoutModTime: false,
			},
		},
	}
	memfsWUI.PathNodes.Set("/",
		_memfsWUI_getNode(memfsWUI, "/", generate__wui))

	memfsWUI.Root = memfsWUI.PathNodes.Get("/")

	var err = memfsWUI.Init()
	if err != nil {
		panic("memfsWUI: " + err.Error())
	}
}
